CREATE PROCEDURE [dbo].[DEV_ClearDatabase]
AS
BEGIN
	SET NOCOUNT ON;
	ALTER TABLE [log].[Command] NOCHECK CONSTRAINT ALL
	ALTER TABLE [dbo].[Robot] NOCHECK CONSTRAINT ALL
	ALTER TABLE [dbo].[Player] NOCHECK CONSTRAINT ALL
	ALTER TABLE [dbo].[Map] NOCHECK CONSTRAINT ALL

	DELETE [log].[Command];
	DELETE [dbo].[Robot];
	DELETE [dbo].[Player];
	DELETE [dbo].[Map];

	DBCC CHECKIDENT ( '[log].[Command]', RESEED, 0)
	DBCC CHECKIDENT ( '[dbo].[Robot]', RESEED, 0)
	DBCC CHECKIDENT ( '[dbo].[Player]', RESEED, 0)
	DBCC CHECKIDENT ( '[dbo].[Map]', RESEED, 0)

	ALTER TABLE [log].[Command] CHECK CONSTRAINT ALL
	ALTER TABLE [dbo].[Robot] CHECK CONSTRAINT ALL
	ALTER TABLE [dbo].[Player] CHECK CONSTRAINT ALL
	ALTER TABLE [dbo].[Map] CHECK CONSTRAINT ALL
END