// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToyRobot.SqlServerModel.DB
{
    public partial class Command
    {
        public int CommandId { get; set; }
        public int RobotId { get; set; }
        public string CommandText { get; set; }
        public DateTime CommandDate { get; set; }
        public string CommandResult { get; set; }
        public int? X { get; set; }
        public int? Y { get; set; }
        public int? OrientationId { get; set; }
        public DateTime? RobotDeletionDate { get; set; }

        public virtual Robot Robot { get; set; }
    }
}