// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ToyRobot.SqlServerModel.DB
{
    public partial class LoadMapsResult
    {
        public int PlayerId { get; set; }
        public int MapId { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public DateTime CreationDate { get; set; }
    }
}
