// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ToyRobot.SqlServerModel.DB
{
    public partial class LoadRobotsResult
    {
        public int PlayerId { get; set; }
        public int MapId { get; set; }
        public int RobotId { get; set; }
        public int? X { get; set; }
        public int? Y { get; set; }
        public int? OrientationId { get; set; }
        public DateTime CreationDate { get; set; }
    }
}
