// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToyRobot.SqlServerModel.DB
{
    public partial class Map
    {
        public Map()
        {
            Robot = new HashSet<Robot>();
        }

        public int MapId { get; set; }
        public int? CreatedByPlayerId { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int MaxRobots { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime? DeletionDate { get; set; }

        public virtual Player CreatedByPlayer { get; set; }
        public virtual ICollection<Robot> Robot { get; set; }
    }
}