// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToyRobot.SqlServerModel.DB
{
    public partial class Robot
    {
        public Robot()
        {
            Command = new HashSet<Command>();
        }

        public int RobotId { get; set; }
        public int PlayerId { get; set; }
        public int MapId { get; set; }
        public int? X { get; set; }
        public int? Y { get; set; }
        public int? OrientationId { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime? DeletionDate { get; set; }

        public virtual Map Map { get; set; }
        public virtual Player Player { get; set; }
        public virtual ICollection<Command> Command { get; set; }
    }
}